-- Make `apply_review` idempotent, so a replayed review cannot double-count.
--
-- The blueprint asserted that offline replay was already safe ("an offline batch
-- replays through the same function"). It was not. There was no idempotency key
-- anywhere, so calling `apply_review` twice with identical arguments produced:
--
--     first : reps = 1, 1 review_event, daily_activity.reviews = 1
--     replay: reps = 2, 2 review_events, daily_activity.reviews = 2
--     (measured, both rows written)
--
-- A duplicated review is not cosmetic. It advances the FSRS schedule for a card
-- the learner reviewed once, inflates `reps` and the daily review count, and
-- skews accuracy — which Language DNA and the recommendation engine both read.
--
-- This is a correctness requirement independent of offline mode, because a
-- retried request, a flaky connection, or a double-tap all replay a review. It is
-- also the prerequisite for the offline queue: a batch that syncs twice, or that
-- half-succeeds and is retried, must be safe.
--
-- The key is generated by the client, one per review, and reused verbatim across
-- every retry. It is scoped to the user, so one learner's key can never suppress
-- another learner's review, and it is nullable so existing callers and historical
-- rows keep working.

ALTER TABLE public.review_events
  ADD COLUMN IF NOT EXISTS client_key uuid;

COMMENT ON COLUMN public.review_events.client_key IS
  'Client-generated idempotency key, one per review, reused across retries. NULL for rows written before this existed.';

-- Partial and unique: uniqueness only has to hold for keys that were actually
-- supplied, and NULLs must not collide with each other.
CREATE UNIQUE INDEX IF NOT EXISTS review_events_client_key_idx
  ON public.review_events (user_id, client_key)
  WHERE client_key IS NOT NULL;

-- The previous 13-argument function is dropped rather than kept, because adding a
-- parameter with a DEFAULT would create a second overload and leave PostgREST to
-- guess which one a named-argument call meant.
DROP FUNCTION IF EXISTS public.apply_review(
  uuid, uuid, text, text, timestamptz, double precision, double precision,
  text, double precision, double precision, double precision, integer, text
);

CREATE OR REPLACE FUNCTION public.apply_review(
  p_user_id        uuid,
  p_item_id        uuid,
  p_language_code  text,
  p_rating         text,
  p_next_due_at    timestamptz,
  p_stability      double precision,
  p_difficulty     double precision,
  p_state          text,
  p_mastery        double precision,
  p_interval_days  double precision DEFAULT NULL,
  p_elapsed_days   double precision DEFAULT NULL,
  p_latency_ms     integer DEFAULT NULL,
  p_mode           text DEFAULT 'review',
  p_client_key     uuid DEFAULT NULL
)
RETURNS public.review_states
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_prev    public.review_states;
  v_row     public.review_states;
  v_correct boolean;
BEGIN
  IF p_user_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'apply_review: user mismatch' USING ERRCODE = '42501';
  END IF;

  IF p_rating NOT IN ('again', 'hard', 'good', 'easy') THEN
    RAISE EXCEPTION 'apply_review: invalid rating %', p_rating USING ERRCODE = '22023';
  END IF;

  -- ---- Idempotency gate ---------------------------------------------------
  -- Only the event insert is gated. If this key has been seen, the review was
  -- already applied in full, so re-applying the schedule would be the bug this
  -- function exists to prevent.
  IF p_client_key IS NOT NULL THEN
    IF EXISTS (
      SELECT 1 FROM public.review_events
      WHERE user_id = p_user_id AND client_key = p_client_key
    ) THEN
      -- Return the card's CURRENT state. The client uses this to settle a queued
      -- item without changing anything; it is deliberately not a replay of the
      -- original response, because the schedule may have moved on since.
      SELECT * INTO v_row
      FROM public.review_states
      WHERE user_id = p_user_id AND item_id = p_item_id;

      RETURN v_row;
    END IF;
  END IF;

  SELECT * INTO v_prev
  FROM public.review_states
  WHERE user_id = p_user_id AND item_id = p_item_id
  FOR UPDATE;

  v_correct := p_rating <> 'again';

  INSERT INTO public.review_events (
    user_id, item_id, language_code, rating, mode,
    state_before, stability_before, difficulty_before,
    interval_days, elapsed_days, latency_ms, client_key
  )
  VALUES (
    p_user_id, p_item_id, p_language_code, p_rating, p_mode,
    v_prev.state, v_prev.stability, v_prev.difficulty,
    p_interval_days, p_elapsed_days, p_latency_ms, p_client_key
  );

  INSERT INTO public.review_states AS rs (
    user_id, item_id, language_code, state, stability, difficulty, due_at,
    last_reviewed_at, reps, successful_reviews, lapses, streak_correct,
    last_rating, mastery
  )
  VALUES (
    p_user_id, p_item_id, p_language_code,
    COALESCE(p_state, 'review'),
    COALESCE(p_stability, 0),
    COALESCE(p_difficulty, 0),
    COALESCE(p_next_due_at, now()),
    now(),
    1,
    CASE WHEN v_correct THEN 1 ELSE 0 END,
    CASE WHEN v_correct THEN 0 ELSE 1 END,
    CASE WHEN v_correct THEN 1 ELSE 0 END,
    p_rating,
    COALESCE(p_mastery, 0)
  )
  ON CONFLICT (user_id, item_id) DO UPDATE SET
    state              = EXCLUDED.state,
    stability          = EXCLUDED.stability,
    difficulty         = EXCLUDED.difficulty,
    due_at             = EXCLUDED.due_at,
    last_reviewed_at   = now(),
    reps               = rs.reps + 1,
    successful_reviews = rs.successful_reviews + CASE WHEN v_correct THEN 1 ELSE 0 END,
    lapses             = rs.lapses + CASE WHEN v_correct THEN 0 ELSE 1 END,
    streak_correct     = CASE WHEN v_correct THEN rs.streak_correct + 1 ELSE 0 END,
    last_rating        = EXCLUDED.last_rating,
    mastery            = EXCLUDED.mastery
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

GRANT EXECUTE ON FUNCTION public.apply_review(
  uuid, uuid, text, text, timestamptz, double precision, double precision,
  text, double precision, double precision, double precision, integer, text, uuid
) TO authenticated;

-- A learner may INSERT their own events but never update them; `client_key` is
-- part of that append-only contract, so replacing it after the fact must not be
-- possible. `tighten-privileges.sql` already revokes UPDATE on this table; this
-- asserts the column is covered by that intent rather than silently assuming it.
REVOKE UPDATE (client_key) ON public.review_events FROM authenticated, anon;
