/**
 * Keeping internal validation text out of the interface.
 *
 * Run:  npm test
 *
 * A screenshot showed "Too small: expected string to have >=2 characters" printed
 * under a correctly selected language. That string was generated by Zod for a bare
 * `.min(2)`, and it is written for whoever reads the stack trace — not for a
 * learner on a phone.
 *
 * The underlying defects are fixed at their source (an unnamed search field, and
 * issue ordering that reported the wrong step). These tests cover the guard that
 * stops the *next* unguarded constraint from reaching a screen, and they pin the
 * distinction that makes it safe: authored copy passes through, machine text does
 * not.
 */

import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  firstUserFacingMessage,
  isUserFacingMessage,
  userFacingMessage,
} from "./errors.ts";

describe("isUserFacingMessage", () => {
  it("rejects the exact string that reached a learner", () => {
    assert.equal(
      isUserFacingMessage("Too small: expected string to have >=2 characters"),
      false,
    );
  });

  it("rejects the common machine-generated shapes", () => {
    const machine = [
      "Too small: expected string to have >=2 characters",
      "Too big: expected number to be <=72",
      "Invalid input: expected string, received undefined",
      "Invalid enum value. Expected 'a' | 'b', received 'c'",
      "Unrecognized key: \"extra\"",
      "Required",
      "ZodError: validation failed",
      'relation "public.items" does not exist',
      "new row violates check constraint",
      "permission denied for table saved_items",
      "Cannot read properties of undefined (reading 'id')",
      "x is not a function",
      "TypeError: undefined is not a function",
    ];
    for (const message of machine) {
      assert.equal(isUserFacingMessage(message), false, `should reject: ${message}`);
    }
  });

  it("keeps copy a person wrote", () => {
    const authored = [
      "Choose at least one reason",
      "Choose at least one area you'd like to improve",
      "Choose your first language",
      "That email and password combination is not right.",
      "Use at least 8 characters",
      "Choose one of the offered study times",
    ];
    for (const message of authored) {
      assert.equal(isUserFacingMessage(message), true, `should keep: ${message}`);
    }
  });

  it("does not swallow a legitimate sentence containing 'expected'", () => {
    // A loose /expected/ pattern would eat this. The patterns are specific for
    // exactly this reason.
    assert.equal(isUserFacingMessage("Choose the expected answer to continue"), true);
  });

  it("treats empty and non-strings as unusable", () => {
    for (const value of ["", "  ", null, undefined, 42, {}]) {
      assert.equal(isUserFacingMessage(value), false);
    }
  });
});

describe("userFacingMessage", () => {
  it("passes authored copy through, trimmed", () => {
    assert.equal(
      userFacingMessage("  Choose at least one reason  ", "fallback"),
      "Choose at least one reason",
    );
  });

  it("substitutes the fallback for machine text", () => {
    assert.equal(
      userFacingMessage("Too small: expected string to have >=2 characters", "Choose your first language"),
      "Choose your first language",
    );
  });

  it("substitutes the fallback when there is no message at all", () => {
    assert.equal(userFacingMessage(undefined, "Something went wrong"), "Something went wrong");
  });

  it("never returns an empty string", () => {
    assert.equal(userFacingMessage("", "Fallback"), "Fallback");
  });
});

describe("firstUserFacingMessage", () => {
  it("skips machine text and returns the first usable message", () => {
    // The realistic case: a field with no authored message fails first, and the
    // readable one after it must still win.
    const issues = [
      { message: "Too small: expected string to have >=2 characters" },
      { message: "Choose at least one area you'd like to improve" },
    ];
    assert.equal(
      firstUserFacingMessage(issues, "Check your answers"),
      "Choose at least one area you'd like to improve",
    );
  });

  it("falls back when every message is machine text", () => {
    const issues = [{ message: "Invalid input: expected string" }, { message: "Required" }];
    assert.equal(firstUserFacingMessage(issues, "Check your answers"), "Check your answers");
  });

  it("falls back on an empty list", () => {
    assert.equal(firstUserFacingMessage([], "Check your answers"), "Check your answers");
    assert.equal(firstUserFacingMessage(undefined, "Check your answers"), "Check your answers");
  });
});
